{{- if .Values.grafanaDatabase.enabled }}
# Database backup storage
apiVersion: objectstorage.giantswarm.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Chart.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.selector" . | nindent 4 }}
  name: giantswarm-{{ .Values.grafanaDatabase.baseUrl }}-{{ .Chart.Name }}-{{ .Values.grafanaDatabase.databaseSuffix }}
  namespace: {{ .Release.Namespace }}
spec:
  name: giantswarm-{{ .Values.grafanaDatabase.baseUrl }}-{{ .Chart.Name }}-{{ .Values.grafanaDatabase.databaseSuffix }}
  expirationPolicy:
    days: 100
  accessRole:
    roleName: giantswarm-{{ .Values.grafanaDatabase.baseUrl }}-{{ .Chart.Name }}-{{ .Values.grafanaDatabase.databaseSuffix }}
    serviceAccountName: {{ .Chart.Name }}-{{ .Values.grafanaDatabase.databaseSuffix }}
    serviceAccountNamespace: {{ .Release.Namespace }}
  tags:
  - key: app
    value: {{ .Chart.Name }}
  - key: installation
    value: {{ .Values.grafanaDatabase.baseUrl }}
  - key: name
    value: giantswarm-{{ .Values.grafanaDatabase.baseUrl }}-{{ .Chart.Name }}-{{ .Values.grafanaDatabase.databaseSuffix }}
{{- end }}