{{- if .Values.grafanaDatabase.enabled }}
# Pod monitor used to monitor the postgresql cluster. We cannot use .spec.enablePodMonitor because we cannot add the observability.giantswarm.io/tenant label
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    observability.giantswarm.io/tenant: giantswarm
  name: {{ .Chart.Name }}-{{ .Values.grafanaDatabase.databaseSuffix }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: {{ .Chart.Name }}-{{ .Values.grafanaDatabase.databaseSuffix }}
  podMetricsEndpoints:
  - port: metrics
{{- end }}