{{- if .Values.database.enabled }}
# Postgresql cluster
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    {{- include "labels.selector" . | nindent 4 }}
  name: {{ .Chart.Name }}-{{ .Values.database.clusterName }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: 2
  storage:
    size: 1Gi
{{- end }}
