apiVersion: v1
name: grafana-app
version: 0.0.0-94a9803231f83493f5fcfdb15bdcda2c66cae87d
appVersion: 7.3.1
kubeVersion: "^1.8.0-0"
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://github.com/grafana/grafana
maintainers:
  - name: zanhsieh
    email: zanhsieh@gmail.com
  - name: rtluckie
    email: rluckie@cisco.com
  - name: maorfr
    email: maor.friedman@redhat.com
  - name: Xtigyro
    email: miroslav.hadzhiev@gmail.com
engine: gotpl
type: application
