{{- if .Values.organizations.giantswarm.enabled }}
apiVersion: observability.giantswarm.io/v1alpha1
kind: GrafanaOrganization
metadata:
  name: giantswarm
spec:
  displayName: Giant Swarm
  rbac:
    admins:
    {{- if .Values.oidc.giantswarm.write_all_group }}
    - {{ .Values.oidc.giantswarm.write_all_group }}
    {{- end }}
    {{- with .Values.oidc.giantswarm.write_all_groups }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
  tenants:
  {{- toYaml .Values.organizations.giantswarm.tenants | nindent 4 }}
{{- end }}
