{{- if .Values.organizations.shared.enabled }}
apiVersion: observability.giantswarm.io/v1alpha1
kind: GrafanaOrganization
metadata:
  name: {{ .Values.organizations.shared.name }}
spec:
  displayName: {{ .Values.organizations.shared.displayName }}
  rbac:
    {{- with .Values.organizations.shared.rbac }}
    admins:
      {{- if $.Values.oidc.giantswarm.write_all_group }}
      - {{ $.Values.oidc.giantswarm.write_all_group }}
      {{- end }}
      {{- with $.Values.oidc.giantswarm.write_all_groups }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- if .editors }}
    editors:
      {{- toYaml .editors | nindent 6 }}
    {{- end }}
    {{- if .viewers }}
    viewers:
      {{- toYaml .viewers | nindent 6 }}
    {{- end }}
    {{- end }}
  tenants:
    {{- toYaml .Values.organizations.shared.tenants | nindent 4 }}
{{- end }}