{{- if and .Values.postgresql.enabled .Values.postgresql.scheduledBackup.enabled (not .Values.postgresql.backup.disabledForCustomer) }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.postgresql.clusterName }}-hourly-backup
  namespace: {{ .Release.Namespace }}
spec:
  backupOwnerReference: {{ .Values.postgresql.scheduledBackup.backupOwnerReference }}
  cluster:
    name: {{ .Values.postgresql.clusterName }}
  schedule: 0 0 * * * *
  {{- end }}
